### ISSUE TITLE
Document required Java version 17+

### ISSUE THREAD

**Issue by 1Maxnet1** [klibio/EclipseInstallationManager#42]
The installation failed for me, as I was not able to execute the JAR-File until I tried it with a more up-to-date version (aka Java 17). Maybe it would be nice to document that in the Readme.md/Homepage and add a little check in the beginning which checks for the JRE version and exits with a meaningful error message when a unsupported version is used.

**Comment by A7exSchin** [comment]
Done with 0.5.4 Release
